on:
  workflow_call:

jobs:
  lint:
    name: Run Prettier and ESLint rules checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
      - name: Run linters
        run: |
          cd template
          yarn lint
